apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignite
  namespace: debezium-pipeline
  labels:
    app: ignite
spec:
  serviceName: ignite-service
  replicas: 2
  selector:
    matchLabels:
      app: ignite
  template:
    metadata:
      labels:
        app: ignite
    spec:
      containers:
      - name: ignite
        image: apacheignite/ignite:3.0.0
        ports:
        - containerPort: 10800
          name: thin-client
        - containerPort: 10300
          name: rest
        - containerPort: 3344
          name: discovery
        env:
        - name: IGNITE_WORK_DIR
          value: /ignite/work
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1g -server -XX:+UseG1GC"
        volumeMounts:
        - name: ignite-storage
          mountPath: /ignite/work
        - name: ignite-config-volume
          mountPath: /ignite/config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /management/v1/node/state
            port: 10300
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/v1/node/state
            port: 10300
          initialDelaySeconds: 60
          periodSeconds: 5
      volumes:
      - name: ignite-config-volume
        configMap:
          name: ignite-config
  volumeClaimTemplates:
  - metadata:
      name: ignite-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
