apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: debezium-pipeline
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: plaintext
  selector:
    app: kafka
