apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: debezium-pipeline
  labels:
    app: kafka-connect
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: rest-api
  selector:
    app: kafka-connect
